Data Pre-processing Flow

In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = sns.load_dataset("titanic")
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
#Check null (.isnull()) column values and their sum (.sum()) with proper sorting(.sort())
data.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [4]:
#Drop a column (Deck)
# data = data.drop('deck',axis=1,inplace=True) or 
data.drop('deck',axis=1,inplace=True) # axis = 1 means column and axis =0 means row
# inplace = True means change in original data

In [17]:
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

1.Imputing values as mode, median, mean etc
for Regression --> mean,median
for Clssification -->mode

In [5]:
# impute missing values with mean/median etc
data['age'] = data['age'].fillna(data['age'].mean())
data.isnull().sum().sort_values(ascending=False)

embark_town    2
embarked       2
sex            0
age            0
survived       0
pclass         0
parch          0
sibsp          0
class          0
fare           0
who            0
adult_male     0
alive          0
alone          0
dtype: int64

In [6]:
# impute missing values with mode etc
data['embark_town'] = data['embark_town'].fillna(data['embark_town'].mode()[0])
data['embarked'] = data['embarked'].fillna(data['embarked'].mode()[0])
data.isnull().sum().sort_values(ascending=False)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

2.Imputing values by using algorithm 
 --> K-Nearest Neighbors (KNN)

In [7]:
df = sns.load_dataset("titanic")
df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [8]:
# Impute Missing values by KNN algorithm
from sklearn.impute import KNNImputer

#Call the knn by the number of neighbours
imputer = KNNImputer(n_neighbors=4)

#impute missing values by KNN imputer
df['age'] = imputer.fit_transform(df[['age']]) # fit means train ans transform means impliment changes by training

#check imputed values
df.isnull().sum().sort_values(ascending=False)

deck           688
embarked         2
embark_town      2
age              0
survived         0
pclass           0
sex              0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

Multiple Imputation by Chained Equation (MICE)

In [9]:
from sklearn.experimental import enable_iterative_imputer #enable
from sklearn.impute import IterativeImputer # import

In [10]:
data = sns.load_dataset('titanic')
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [12]:
df.dtypes

survived          int64
pclass            int64
sex                 str
age             float64
sibsp             int64
parch             int64
fare            float64
embarked            str
class          category
who                 str
adult_male         bool
deck           category
embark_town         str
alive               str
alone              bool
dtype: object

Converting Categorical data columns to numerical one using automatical methods like LabelEncoder

In [13]:
#we take all str and category columns for labelen-Coding
from sklearn.preprocessing import LabelEncoder

#columns to encode
columns_to_encode = ['sex', 'embarked', 'who', 'deck', 'class', 'embark_town', 'alive']

# 3dictionary to store labelencoder for each column
label_encoders = {}

#loop to apply labelencoder for the columns
for col in columns_to_encode:
    # call labelencoder object
    le = LabelEncoder()
    # train and transform
    df[col] = le.fit_transform(df[col])
    # add in the dictionary one-one
    label_encoders[col] = le
    
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,7,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,2,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,7,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,7,2,0,True

Imputing the missing values by iterative-imputer

In [14]:
imputer  = IterativeImputer(max_iter=10) #max-iterator means who many times algo check the values by iteration
#columns to impute
columns_to_impute = ['age', 'embark_town', 'embarked', 'deck']

#loop
for col in columns_to_impute:
    df[col] = imputer.fit_transform(df[[col]])
# check missing values
df.isnull().sum().sort_values(ascending=False)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [16]:
#Inverse transform for encoded  columns
for col in columns_to_encode:
    #retreive the corresponding lableencoder for the column
    le = label_encoders[col]
    #inverse transform the data and convert to integer type
    df[col] = le.inverse_transform(df[col].astype(int))
    
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Regression Imputation

In [ ]:
data = sns.load_dataset("titanic")
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
#Check missing values
data.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [ ]:
# # By regression imputer (iterative_imputer)
# from sklearn.experimental import enable_iterative_imputer
# from sklearn.impute import IterativeImputer
# impute = IterativeImputer(max_iter=20)
# data['age'] = impute.fit_transform(data[['age']])

# data.isnull().sum().sort_values(ascending=False)

deck           688
embarked         2
embark_town      2
age              0
survived         0
pclass           0
sex              0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

Random Forest for Imputing Missing Values
bagging , Bosting, Esamble

In [46]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error, r2_score
from sklearn.impute import SimpleImputer

df = sns.load_dataset('titanic')

df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [ ]:
# Remove deck column
df.drop('deck',axis=1,inplace=True)

df.isnull().sum().sort_values(ascending=False)

age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
parch            0
sibsp            0
class            0
fare             0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

In [22]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    str
 12  alive        891 non-null    str
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), str(5)
memory usage: 79.4 KB

In [27]:
# Label to encode (encode means convert the dtr,category type to integer or  other)
from sklearn.preprocessing import LabelEncoder
# columns to encoding required
columns_to_encode = ['sex', 'embarked', 'class', 'who', 'embark_town', 'alive']

# Dictionary for label encoders
label_encoders = {}

#loop to iterate all values
for col in columns_to_encode:
    #call lable encoder and store in variable then use that variable
    le = LabelEncoder()
    # Fit and transform
    df[col] = le.fit_transform(df[col])
    #store in dictionary
    label_encoders[col] = le
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [ ]:
# split the dataset into two parts : one with missing values and other is non-missing values
df_with_missing = df[df['age'].isna()]
#drop all rows with missing values
df_without_missing = df.dropna()

     survived  pclass  sex  age  sibsp  parch     fare  embarked  class  who  \
5           0       3    1  NaN      0      0   8.4583         1      2    1
17          1       2    1  NaN      0      0  13.0000         2      1    1
19          1       3    0  NaN      0      0   7.2250         0      2    2
26          0       3    1  NaN      0      0   7.2250         0      2    1
28          1       3    0  NaN      0      0   7.8792         1      2    2
..        ...     ...  ...  ...    ...    ...      ...       ...    ...  ...
859         0       3    1  NaN      0      0   7.2292         0      2    1
863         0       3    0  NaN      8      2  69.5500         2      2    2
868         0       3    1  NaN      0      0   9.5000         2      2    1
878         0       3    1  NaN      0      0   7.8958         2      2    1
888         0       3    0  NaN      1      2  23.4500         2      2    2

     adult_male  embark_town  alive  alone
5          True            1      0   True
17         True            2      1   True
19        False            0      1   True
26         True            0      0   True
28        False            1      1   True
..          ...          ...    ...    ...
859        True            0      0   True
863       False            2      0  False
868        True            2      0   True
878        True            2      0   True
888       False            2      0  False

[177 rows x 14 columns]

In [30]:
print("original dataset",df.shape)
print("Dataset with missing values",df_with_missing.shape)
print("Dataset without missing values",df_without_missing.shape)

original dataset (891, 14)
Dataset with missing values (177, 14)
Dataset without missing values (714, 14)

In [32]:
df_with_missing.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
5,0,3,1,NaN,0,0,8.4583,1,2,1,True,1,0,True
17,1,2,1,NaN,0,0,13.0000,2,1,1,True,2,1,True
19,1,3,0,NaN,0,0,7.2250,0,2,2,False,0,1,True
26,0,3,1,NaN,0,0,7.2250,0,2,1,True,0,0,True
28,1,3,0,NaN,0,0,7.8792,1,2,2,False,1,1,True

In [33]:
df_without_missing.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [39]:
#check columns name
print(df.columns)

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='str')

In [48]:
# import regressor model
from sklearn.ensemble import RandomForestRegressor
# predicta the missing values by random forest imputation
X = df_without_missing.drop(['age'],axis=1)
y = df_without_missing['age']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=42)

#using random forest model
rf_model = RandomForestRegressor(n_estimators = 100, random_state=42)
rf_model.fit(X_train,y_train)

#Evaluate the model
y_pred = rf_model.predict(X_test)
print("RMSE",np.sqrt(mean_squared_error(y_test, y_pred)))
print("r2 score",r2_score(y_test, y_pred))
print("MAE",mean_absolute_error(y_test, y_pred))
print("MAPE",mean_absolute_percentage_error(y_test, y_pred))

RMSE 11.081223149632903
r2 score 0.33769835833249207
MAE 8.66658629114667
MAPE 0.40838522040142516

In [52]:
y_pred = rf_model.predict(df_with_missing.drop(['age'], axis=1))

In [56]:
print(y_pred)

[32.97658333 35.64221825 18.347      35.57148611 20.65142857 26.7619855
 36.648      18.63142857 21.80633333 33.55618169 31.06587652 35.90741667
 18.63142857 24.824      31.03       39.405      25.849      26.7619855
 31.06587652 19.41142857 31.06587652 31.06587652 26.7619855  26.27095821
 29.23514286 31.06587652 48.25650595 27.94       31.87071429 31.99628481
 30.015      20.85816667 33.755      60.19168831 26.00185714 26.24316667
 28.91733333 49.31       28.55277778 48.25650595 18.63142857 20.85816667
 33.78929167 26.7619855  26.63       32.01066667 28.22883333 28.55277778
 31.99628481 29.72904762 48.25650595 27.67733333 56.26333333 18.63142857
 34.65645944 60.44168831 39.405      35.7725     18.63142857 24.78266667
 34.305      31.06587652 31.602      20.85816667 25.296      36.97133333
 26.7619855  24.85777778 55.52       35.57148611 20.65142857 20.65142857
 35.90741667 18.001      18.63142857 39.47333333 26.7619855  30.16908333
 26.63       26.7619855  24.02805952 34.65645944 29.42072422 33.55618169
 31.99628481 48.25650595 24.85777778 23.11209163 24.83533333 31.06587652
 38.22933333 48.25650595 31.06587652 34.65645944 30.16908333 31.99628481
 47.13       34.65645944 26.63       24.83533333 23.08233333 26.63047619
 23.518125   40.09880556 31.06587652 34.95423214 35.57148611 26.96691667
 27.47       26.96691667 28.         23.78047619 29.70866667 37.26078571
 26.547      48.25650595 31.06587652 29.42072422 26.96691667 18.63142857
 27.61883333 32.55166667 31.06587652 27.513375   33.66772547 35.57148611
 26.7619855  43.55       26.58728571 28.55277778 48.25650595 30.16908333
 41.999      26.988      29.31457143 35.71033333 26.7619855  20.92142857
 26.7619855  29.13884783 38.22933333 34.65645944 25.32811441 29.31457143
 16.876      25.849      57.97458028 30.42173214 16.876      34.65645944
 26.7619855  26.7619855  64.9625     23.78047619 45.39       34.30619444
 35.57148611 48.25650595 30.16908333 34.02       48.25650595 26.24316667
 54.35       41.999      25.02884524 30.97725    29.83383333 26.96691667
 31.06587652 36.72       20.85816667 37.63666667 26.96691667 26.24316667
 24.81692641 26.7619855  32.61      ]

In [54]:
# remove warnings
import warnings
warnings.filterwarnings('ignore')

#replace with predicted values
df_with_missing['age'] = y_pred
df_with_missing.isnull().sum().sort_values(ascending=False)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [55]:
df_with_missing.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
5,0,3,1,32.976583,0,0,8.4583,1,2,1,True,1,0,True
17,1,2,1,35.642218,0,0,13.0000,2,1,1,True,2,1,True
19,1,3,0,18.347000,0,0,7.2250,0,2,2,False,0,1,True
26,0,3,1,35.571486,0,0,7.2250,0,2,1,True,0,0,True
28,1,3,0,20.651429,0,0,7.8792,1,2,2,False,1,1,True